language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
env:
    - DJANGO_VERSION=1.2
    - DJANGO_VERSION=1.3
install: pip install Django=$DJANGO_VERSION markdown docutils --use-mirrors
script: python setup.py test
notifications:
    email:
        - jturk@sunlightfoundation.com
